package org.java.feature.extractor.constants;

public class Constants {
    
    public static final String SOURCE_ROOT_PATH = "C:\\bigclonebench-selected-files-dataset\\original-files\\java";
    public static final String NEW_PATH = "C:\\bigclonebench-selected-files-dataset\\comments-removed-files-from-original-files";
    public static final String[] methodStrings = new String[]{
            "    public static void validatePhoneNumber(\n" + "        String phoneNumber1, String phoneNumber2) {\n" + "      \n" + "        final int numberLength = 10;\n" + "        \n" + "        // Valid in JDK 8 and later:\n" + "       \n" + "        // int numberLength = 10;\n" + "       \n" + "        class PhoneNumber {\n" + "            \n" + "            String formattedPhoneNumber = null;\n" + "\n" + "            PhoneNumber(String phoneNumber){\n" + "                // numberLength = 7;\n" + "                String currentNumber = phoneNumber.replaceAll(\n" + "                  regularExpression, \"\");\n" + "                if (currentNumber.length() == numberLength)\n" + "                    formattedPhoneNumber = currentNumber;\n" + "                else\n" + "                    formattedPhoneNumber = null;\n" + "            }\n" + "\n" + "            public String getNumber() {\n" + "                return formattedPhoneNumber;\n" + "            }\n" + "            \n" + "            // Valid in JDK 8 and later:\n" + "\n" + "//            public void printOriginalNumbers() {\n" + "//                System.out.println(\"Original numbers are \" + phoneNumber1 +\n" + "//                    \" and \" + phoneNumber2);\n" + "//            }\n" + "        }\n" + "\n" + "        PhoneNumber myNumber1 = new PhoneNumber(phoneNumber1);\n" + "        PhoneNumber myNumber2 = new PhoneNumber(phoneNumber2);\n" + "        \n" + "        // Valid in JDK 8 and later:\n" + "\n" + "//        myNumber1.printOriginalNumbers();\n" + "\n" + "        if (myNumber1.getNumber() == null) \n" + "            System.out.println(\"First number is invalid\");\n" + "        else\n" + "            System.out.println(\"First number is \" + myNumber1.getNumber());\n" + "        if (myNumber2.getNumber() == null)\n" + "            System.out.println(\"Second number is invalid\");\n" + "        else\n" + "            System.out.println(\"Second number is \" + myNumber2.getNumber());\n" + "\n" + "    }",
            "public void sayHello() {\n" + "        // local class\n" + "        class EnglishGreeting implements HelloWorld {\n" + "            String name = \"world\";\n" + "            public void greet() {\n" + "                greetSomeone(\"world\");\n" + "            }\n" + "            public void greetSomeone(String someone) {\n" + "                name = someone;\n" + "                System.out.println(\"Hello \" + name);\n" + "            }\n" + "        }\n" + "      \n" + "        HelloWorld englishGreeting = new EnglishGreeting();\n" + "        // anonymous class\n" + "        HelloWorld frenchGreeting = new HelloWorld() {\n" + "            String name = \"tout le monde\";\n" + "            public void greet() {\n" + "                greetSomeone(\"tout le monde\");\n" + "            }\n" + "            public void greetSomeone(String someone) {\n" + "                name = someone;\n" + "                System.out.println(\"Salut \" + name);\n" + "            }\n" + "        };\n" + "        // anonymous class\n" + "        HelloWorld spanishGreeting = new HelloWorld() {\n" + "            String name = \"mundo\";\n" + "            public void greet() {\n" + "                greetSomeone(\"mundo\");\n" + "            }\n" + "            public void greetSomeone(String someone) {\n" + "                name = someone;\n" + "                System.out.println(\"Hola, \" + name);\n" + "            }\n" + "        };\n" + "        englishGreeting.greet();\n" + "        frenchGreeting.greetSomeone(\"Fred\");\n" + "        spanishGreeting.greet();\n" + "    }"
    };
    public static final String classStart = "class A {\n";
    public static final String classEnd = "\n}";
}
